### ISSUE TITLE
Add tournament size and minimum entries filters on landing page

### ISSUE THREAD

**Issue by Soujds** [EDH-Top-16/edhtop16#141]
First of all very nice changes in the look and feel of the platform.

It would be great to have advanced segmentation otions as we had before, like dates, tournamet population, atc. This request becomes more needed since the changes of the banlist, so it would be great if we can filter at least from the 09.23 onwards to see "tournaments under the new ban list"

Regards

**Comment by SMYLOX** [comment]
> First of all very nice changes in the look and feel of the platform.
> 
> It would be great to have advanced segmentation otions as we had before, like dates, tournamet population, atc. This request becomes more needed since the changes of the banlist, so it would be great if we can filter at least from the 09.23 onwards to see "tournaments under the new ban list"
> 
> Regards

Yes please!!

Never change a running system... especially when your system was good. 
Please bring back all the filter options.

Thanks for your work btw!

**Comment by JasonQiu21** [comment]
Hi! We had some bad stability issues, so we felt compelled to release v2 as it is. That being said, plans to bring back a table view like that of v1exist.

**Comment by rrdelaney** [comment]
@Soujds Thank you for the feedback!

Specifically, for the landing page we'd like to re-add:

* Minimum entries filter for each commander
* Tournament size filter for entries considered when calculating stats.

**Comment by rrdelaney** [comment]
Minimum entries is done, tournament size is not yet.
