### ISSUE TITLE
Allow toggling between list and grid views

### ISSUE THREAD

**Issue by fjluartes** [EDH-Top-16/edhtop16#143]
**List View**

Option to switch between list and grid views in both commanders and tournaments tabs.

**List and Grid Views**

Option to check for more than 24 entries in both tabs (similar to old list layout). If I wanted to play a fringe cEDH commander I can check the list in the rank 100+

**Comment by rrdelaney** [comment]
We'd probably like to implement this for both the landing page and decklists page, seems less necessary for the list of tournaments.
