### ISSUE TITLE
Add time period for post-bans

### ISSUE THREAD

**Issue by rrdelaney** [EDH-Top-16/edhtop16#152]
It would be nice to filter entries to only post-bans using each of our "Time Period" selectors, both on the landing page and when looking at decklists.

**Comment by Griffinw29** [comment]
Commenting to get issue assigned to me!

**Comment by rrdelaney** [comment]
@Griffinw29 here is some seed data to help you out: [seed data.zip](https://github.com/user-attachments/files/18055111/seed.data.zip)

Just unzip this into `prisma/data`

**Comment by Griffinw29** [comment]
Thank you for the additional data! I am trying to push my local branch for this issue, and it seems as though I do not have permission to do so.  Would you be able to edit my permissions so that I can?

**Comment by Griffinw29** [comment]
PR: https://github.com/EDH-Top-16/edhtop16/pull/203
