### ISSUE TITLE
Only show top cuts

### ISSUE THREAD

**Issue by znayer** [EDH-Top-16/edhtop16#39]
Instead of cataloguing for the first 16 standings for conversion and other metrics, instead only account for the top cuts.

We can use the topCut from the Eminence API to determine how many decks to take for that information.

Right now some tourneys with 20 people, we show their top 16. This would address such things.

**Comment by JasonQiu21** [comment]
moving this issue to rewrite; top cuts and conversion rate will be calculated server-side with new routes for commander view, player view
