### ISSUE TITLE
Entries equal to N does not work

### ISSUE THREAD

**Issue by g00gol** [EDH-Top-16/edhtop16#42]
**Describe the bug**
Filtering by `entries = N`  does not work and will show no entries matching that criteria even if there is

**To Reproduce**
1. Go to Commander View
2. Click on `entries = N` and input some entry amount that shows up on the table
3. No entries show up

**Expected behavior**
Entries show up

**Screenshots**
(showing we have entries = 5)
![image](https://github.com/EDH-Top-16/edhtop16/assets/38109082/5a0a89c9-112d-4f09-8226-b329a1c59141)
(screenshot of not working)
![image](https://github.com/EDH-Top-16/edhtop16/assets/38109082/f5346888-5a27-4339-820c-d7a269bafa15)

**Additional context**

**Comment by JasonQiu21** [comment]
In line 102 of `Commanders.js` change:
```js
  if (entries) {
    filteredCommanders = filteredCommanders.filter((el) => {
      if (Object.keys(entries)[0] === "$gte") {
        return el.count >= entries["$gte"];
      } else if (Object.keys(entries)[0] === "$lte") {
        return el.count <= entries["$lte"];
      } else {
        return el.count === entries;
      }
    });
  }
```

to:

```js
  if (entries) {
    filteredCommanders = filteredCommanders.filter((el) => {
      if (Object.keys(entries)[0] === "$gte") {
        return el.count >= entries["$gte"];
      } else if (Object.keys(entries)[0] === "$lte") {
        return el.count <= entries["$lte"];
      } else if (Object.keys(entries)[0] === "$eq"){
        return el.count === entries["$eq"];
      } else {
        return true;
      }
    });
  }
 ```
