### ISSUE TITLE
Possible Data Issue For Tournament Results

### ISSUE THREAD

**Issue by nvander1** [EDH-Top-16/edhtop16#53]
**Describe the bug**
On the API and on the standings page for [Punt City](https://edhtop16.com/tournament/PuntCity?tourney_filter__TID=PuntCity), it seems that several players have multiple standings listed.

**To Reproduce**
1. Go to https://edhtop16.com/tournament/PuntCity?tourney_filter__TID=PuntCity
2. Scroll down and you will see that some people are listed with multiple standings.
  i. Take "Michael Punj" for example. This player is listed with standings 11 & 12.
  ii. On both records, the only difference is the standing number.
  iii. Decklists, names, win/loss/draw, and win percentage is the same between these records.

**Expected behavior**
I expect that a player can't finish in two standings in the same tournament.

**Screenshots**

![image](https://github.com/EDH-Top-16/edhtop16/assets/11447895/dd1f7815-c848-472b-9c4f-18360ab10181)

**Additional context**

I noticed this while doing some analysis on results I obtained from the API.

**Comment by nvander1** [comment]
There may be duplicates on other tournaments as well.

To reproduce:
- Download data from the API
  - ```
    curl -X POST \
    -H "Content-Type: application/json" \
    -H "Accept: application/json" \
    https://edhtop16.com/api/req \
    > entries.json
  
    
    curl -X POST \
    -H "Content-Type: application/json" \
    -H "Accept: application/json" \
    https://edhtop16.com/api/list_tourneys \
    > tournaments.json
    ```
- Create a file, "issues.sql", with the following contents
  - ```
    select standing,
       name,
       profile,
       decklist,
       tournamentName,
       dateCreated,
       count(standing) over (partition by tournamentName, dateCreated, name, profile, decklist) as standing_counts
     from 'entries.json'
    qualify standing_counts > 1
    order by tournamentName, dateCreated desc, name, profile, decklist, standing asc
    ```
- Run the query in [duckDB](https://duckdb.org/)
  - ```
    duckdb < issues.sql
    ```

![image](https://github.com/EDH-Top-16/edhtop16/assets/11447895/046c6a2c-a7be-425a-a25d-7198ffd4421e)

**Comment by nvander1** [comment]
@JasonQiu21 @g00gol After posting this issue, I noticed that you all have [started a rewrite for the website](https://github.com/EDH-Top-16/edhtop16-v2). 

Should I instead open this issue on that repository, or keep it here?

**Comment by g00gol** [comment]
@nvander1 Here's fine. @JasonQiu21 will take a look at the issue rn

**Comment by JasonQiu21** [comment]
@nvander1 does this issue occur in specific instances or for every tournament?

**Comment by nvander1** [comment]
I see it only for the following tournaments:

```csv
tournamentName,dateCreated
"Tavern of Souls Spring 2K",1687586400
"ka0s Treasure Series 4",1686974400
"CCS Grand Opening cEDH Timetwister Tournament ",1685764800
"COMMNANDERGEDDON 2",1683900000
"Mox Masters May 23",1683381600
"cEDH RBP 18 de MARZO",1678991637
"Mox Masters February 23",1677333600
"Mox Masters January 23",1674918000
"Mox Masters December 22",1670054400
"Mox Masters October 22",1664607601
"Punt City",1661608800
```

**Comment by JasonQiu21** [comment]
Alright, spoke with @znayer and it's probably an issue when they changed bracket standings to reflect actual top cuts (so first is the person who won the tournament, not the person with the most points); I'm closing this issue and moving the effort to fix this to the rewrite. This issue shouldn't spread, @nvander1 please raise something if you notice it, and thanks for pointing this out. I'll let you know when the live db gets fixed.

**Comment by JasonQiu21** [comment]
@nvander1 can you check again if you still see duplicates?

**Comment by nvander1** [comment]
@JasonQiu21 Yes I still see one.
![image](https://github.com/EDH-Top-16/edhtop16/assets/11447895/aad7973e-6f1b-4b41-ae09-56fa121bf195)

**Comment by JasonQiu21** [comment]
ok, I'm not sure how or why that one's still there but running it again seems to have removed it; one last check @nvander1 (and thanks for helping check for me)

**Comment by nvander1** [comment]
Looks good to me! Nice job everyone!
