### ISSUE TITLE
https cert fails when "www." is in url

### ISSUE THREAD

**Issue by gcarvellas** [EDH-Top-16/edhtop16#54]
**Describe the bug**
When going to, https://www.edhtop16.com/ cert fails
but when going to https://edhtop16.com/ cert passes

Consistently reproducible on Mozilla Firefox 117.0.1

Not sure if this server is using a proxy, but it's likely a proxy rule is missing to handle `www.` urls

**Screenshots**
![image](https://github.com/EDH-Top-16/edhtop16/assets/71856311/2cc438bc-d17a-4bd7-92db-e81ba0324b8e)
![image](https://github.com/EDH-Top-16/edhtop16/assets/71856311/2d8149a6-1e82-4c61-b824-7626f07b5f7e)

**Comment by JasonQiu21** [comment]
fixed
