### ISSUE TITLE
Frontend sends 4 identical requests

### ISSUE THREAD

**Issue by n4thal** [EDH-Top-16/edhtop16#55]
**Describe the bug**
When reloading the site without cache,
the same request is sent 4 times.

**To Reproduce**
1. Open some arbitrary page like https://edhtop16.com/tournaments?tourney_filter__size__%24gte=64&tourney_filter__dateCreated__%24gte=1666022517 in Chrome.
2. Open developer tools to track requests and loading.
3. Refresh the site without cache (right-click reload button select empty cache and hard reload)
4. Result is shown after 2 minutes for me.

**Expected behavior**
Only a single request should be sent and resulting data is shared between components to save bandwith.

**Screenshots**
![image](https://github.com/EDH-Top-16/edhtop16/assets/13086467/b57c1371-eda0-46fa-9f0b-840227d42eda)

**Additional context**
I marked the 2 hhuge blocking requests (bundle.js and /api/req) in the screenshot.
Probably good idea to reevaluate issue #20 since there is alot more data being sent now and it will keep growing moving on.

PS: Keep up the good work!

**Comment by JasonQiu21** [comment]
issue also exists on firefox - @g00gol are we addressing this in the rewrite or should I make a fix
