### ISSUE TITLE
TODO: API docs

### ISSUE THREAD

**Issue by g00gol** [EDH-Top-16/edhtop16#6]

**Comment by JasonQiu21** [comment]
@g00gol can you add a button on the nav bar and a page for the docs? I'll put them there as well as in a markdown file.

**Comment by JasonQiu21** [comment]
Added a markdown document with documentation. TODO: expand and move to webpage. Still waiting on @g00gol.

https://github.com/JasonQiu21/cedhtop16/commit/e93cda42a3a8008ac609d3a9313ecca2a419e23b

**Comment by JasonQiu21** [comment]
Moving this issue to rewrite; auto-generating docs w/ fastAPI
